### PR TITLE
resolves #633 Introduce PUPPETEER_PRINT_TIMEOUT for puppeteer pdf rendering

### LINKED ISSUE #633: Bug in setting puppeteer timeouts
The pull request #236 did not change the puppeteer rendering timeout - it changes the time asciidoc-web-pdf waits for puppeteer.

According to [puppeteer pdf options](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions) a timeout shall be passed to the page.pdf() call instead.

Rendering of complex documents on slow machines could easily exceed the 30s limit and no matter what I configure for the rendering timeout, puppeteer always throws a timeout exception after 30s.

I created a fix #632 for this issue

### PR DESCRIPTION
**Pull request by siaccarino**
The pull request [#236](https://github.com/Mogztter/asciidoctor-web-pdf/pull/236) did not change the puppeteer rendering timeout - it changes the time asciidoc-web-pdf waits for puppeteer.

According to [puppeteer pdf options](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions) a timeout shall be passed to the page.pdf() call instead.

Rendering of complex documents on slow machines could easily exceed the 30s limit.

Solution: Introduce a PUPPETEER_PRINT_TIMEOUT environment variable that is passed to puppeteer - see [puppeteer pdf timeout option](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions).

Issue: #633

### CODE REVIEW

File: lib/browser.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ class Browser {
       await page.goto(url, options)
     }
     // watchdog
-    await page.waitForFunction('window.AsciidoctorPDF === undefined || window.AsciidoctorPDF.status === undefined || window.AsciidoctorPDF.status === "ready"', { timeout: this.renderingTimeout })
+    await page.waitForFunction('window.AsciidoctorPDF === undefined || window.AsciidoctorPDF.status === undefined || window.AsciidoctorPDF.status === "ready"')
```
Comment (Mogztter) [inline lib/browser.js:76]: Both timeouts are useful.
This timeout will make sure that Paged.js (JavaScript) completes this task in a reasonable time.

The rendering timeout is the time taken by Paged.js to create paginated content from an HTML document.

File: lib/converter.js [hunk 2]
```diff
@@ -107,6 +107,9 @@ async function convert (processor, inputFile, options, timings, watch, preview)
         pdfOptions.format = format // Paper format. If set, takes priority over width or height options. Defaults to 'Letter'.
       }
 
+      // set the puppeteer render timeout (https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions)
+      pdfOptions.timeout = browserInstance.renderingTimeout;
```
Comment (Mogztter) [inline lib/converter.js:111]: We should configure a specific timeout, see: https://github.com/Mogztter/asciidoctor-web-pdf/issues/612#issuecomment-1028033740
We can also set this value when we declare/initialize the `pdfOptions` object.

File: lib/converter.js [hunk 3]
```diff
@@ -89,10 +89,14 @@ async function convert (processor, inputFile, options, timings, watch, preview)
   }
   try {
     const page = await browserInstance.goto(`file://${tempFile}`, preview)
+    const puppeteerDefaultTimeout = process.env.PUPPETEER_DEFAULT_TIMEOUT
```
Comment (siaccarino) [inline lib/converter.js:92]: could be taken from browser instance but in terms of dependency reduction this might be better

**Comment by Mogztter** [comment]
Looks good!
One last thing, could you please update the `console.log` message to include this new environment variable:

```
> TIP: You can configure the timeout in milliseconds using PUPPETEER_DEFAULT_TIMEOUT, PUPPETEER_NAVIGATION_TIMEOUT, PUPPETEER_RENDERING_TIMEOUT or PUPPETEER_PRINT_TIMEOUT environment variables.
```

As mentioned in https://github.com/Mogztter/asciidoctor-web-pdf/issues/612#issuecomment-1028081320 it would be better to create a separate 'TIP' for each timeout but for now it's good enough. We can revisit this logic later in a follow-up pull request.

**Review by Mogztter — APPROVED** [review]
All good, thanks!
